### ISSUE TITLE
Getting error using this project

### ISSUE THREAD

**Issue by joshisimt** [TechPrimers/spring-boot-mysql-example#2]
Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Unsatisfied dependency expressed through method 'entityManagerFactory' parameter 0; nested exception is org.springframework.beans

**Comment by MovingToWeb** [comment]
Hi @joshisimt 
You need a local mysql instance running for this program to connect.
hence you see this connectivity issue
